version: "3.8"

services:
  server:
    container_name: dev_go_server
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/app
    restart: always
